<?php
declare(strict_types=1);

namespace labo86\rdtas;


class ErrMsg
{

    const SOME_SERVICES_PARAMETER_TYPES_ARE_NOT_SUPPORTED = "SOME_SERVICES_PARAMETER_TYPES_ARE_NOT_SUPPORTED";
    const SERVICE_PARAMETER_TYPE_IS_NOT_SUPPORTED = "SERVICE_PARAMETER_TYPE_IS_NOT_SUPPORTED";
    const UNSUPPORTED_TYPE_IN_REQUEST = "SERVICE_PARAMETER_TYPE_IS_NOT_SUPPORTED";
    const ERROR_OBTAINING_PARAMETER_VALUE_LIST = "ERROR_OBTAINING_PARAMETER_VALUE_LIST";
    const ERROR_DOWNLOADING_JS_COMPONENT = "ERROR_DOWNLOADING_JS_COMPONENT";
    const ERROR_AT_OPENING_FILE = "ERROR_AT_OPENING_FILE";
    const ERROR_REMOVING_FILE_OR_DIR = "ERROR_REMOVING_FILE_OR_DIR";
    const TARGET_DIRECTORY_IS_NOT_A_DIRECTORY = "TARGET_DIRECTORY_IS_NOT_A_DIRECTORY";
    const FORMAT_ERROR_IN_FILE_CONTENTS = "FORMAT_ERROR_IN_FILE_CONTENTS";
    const ERROR_OPENING_ARRAY_FROM_FILE = "ERROR_OPENING_ARRAY_FROM_FILE";
    const ERROR_WRITING_ARRAY_IN_FILE = "ERROR_WRITING_ARRAY_IN_FILE";
    const STRING_IS_NOT_A_VALID_JSON = "STRING_IS_NOT_A_VALID_JSON";
    const DATA_IS_NOT_JSON_COMPATIBLE = "DATA_IS_NOT_JSON_COMPATIBLE";
    const COMPONENT_DOES_NOT_EXIST = "COMPONENT_DOES_NOT_EXIST";
    const COMPONENT_DOES_NOT_HAVE_LABEL = "COMPONENT_DOES_NOT_HAVE_LABEL";
    const COMPONENT_DOES_NOT_HAVE_ID = "COMPONENT_DOES_NOT_HAVE_ID";
    const MODULE_CONFIG_DOES_NOT_EXIST = "MODULE_CONFIG_DOES_NOT_EXIST";
    const NO_ROW_HAS_CHANGED = "NO_ROW_HAS_CHANGED";
    const ERROR_AT_UPDATING = "ERROR_AT_UPDATING";
    const ERROR_AT_SELECTING_ALL_ROWS = "ERROR_AT_SELECTING_ALL_ROWS";
    const ERROR_AT_SELECTING_ROW = "ERROR_AT_SELECTING_ROW";
    const ERROR_PREPARING_EXCEPTION = "ERROR_PREPARING_EXCEPTION";
    const SELECT_RETURNS_NO_ROWS = "SELECT_RETURNS_NO_ROWS";
    const ERROR_EXECUTING_QUERY = "ERROR_EXECUTING_QUERY";
    const SESSION_EXPIRED = "SESSION_EXPIRED";
    const SESSION_INACTIVE = "SESSION_INACTIVE" ;
    const WRONG_PASSWORD = "WRONG_PASSWORD";
    const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";
    const SESSION_DOES_NOT_EXIST = "SESSION_DOES_NOT_EXIST";
    const USER_DOES_NOT_HAVE_PERMISSION = "USER_DOES_NOT_HAVE_PERMISSION";
    const ERROR_CREATING_USER = "ERROR_CREATING_USER";
    const ERROR_CREATING_DATABASE = "ERROR_CREATING_DATABASE";
    const NULL_FOLDER_DIR = "NULL_FOLDER_DIR";
    const NULL_DATABASE_SCHEMA = "NULL_DATABASE_SCHEMA";
    const DATABASE_SCHEMA_FILE_DOES_NOT_EXIST = "DATABASE_SCHEMA_FILE_DOES_NOT_EXIST";
    const NULL_DATABASE_PASSWORD = "NULL_DATABASE_PASSWORD";
    const NULL_DATABASE_USER = "NULL_DATABASE_USER";
    const NULL_DATABASE_NAME = "NULL_DATABASE_NAME";
    const INVALID_DATABASE_TYPE = "INVALID_DATABASE_TYPE";
    const MODULE_DOES_NOT_EXIST = "MODULE_DOES_NOT_EXIST";
    const ERROR_DOES_NOT_EXIST =  "ERROR_DOES_NOT_EXIST";
}